CREATE DATABASE ESPECTACULOS;


CREATE TABLE RECINTOS (
    COD_RECINTO INT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    HORARIO VARCHAR(100) NOT NULL
);
CREATE TABLE ESPECTADORES (
    DNI_CLIENTE VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    NTARJETA VARCHAR(50) NOT NULL
);
CREATE TABLE ESPECTACULOS (
    COD_ESPECTACULO INT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    FECHA_INICIAL DATE NOT NULL,
    FECHA_FINAL DATE NOT NULL,
    INTERPRETE VARCHAR(255) NOT NULL,
    COD_RECINTO INT NOT NULL,
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO),
    CHECK (FECHA_FINAL >= FECHA_INICIAL)
);
CREATE TABLE ZONAS_RECINTOS (
    COD_RECINTO INT NOT NULL,
    ZONA VARCHAR(50) NOT NULL,
    CAPACIDAD INT NOT NULL CHECK (CAPACIDAD > 0),
    PRIMARY KEY (COD_RECINTO, ZONA),
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO)
);
CREATE TABLE PRECIOS_ESPECTACULOS (
    COD_ESPECTACULO INT NOT NULL,
    COD_RECINTO INT NOT NULL,
    ZONA VARCHAR(50) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL CHECK (PRECIO > 0),
    PRIMARY KEY (COD_ESPECTACULO, COD_RECINTO, ZONA),
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO),
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO),
    FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS(COD_RECINTO, ZONA)
);
CREATE TABLE ASIENTOS (
    COD_RECINTO INT NOT NULL,
    ZONA VARCHAR(50) NOT NULL,
    FILA VARCHAR(10) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    PRIMARY KEY (COD_RECINTO, ZONA, FILA, NUMERO),
    FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS(COD_RECINTO, ZONA)
);
CREATE TABLE REPRESENTACIONES (
    COD_ESPECTACULO INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    PRIMARY KEY (COD_ESPECTACULO, FECHA, HORA),
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO)
);
CREATE TABLE ENTRADAS (
    COD_ESPECTACULO INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    COD_RECINTO INT NOT NULL,
    FILA VARCHAR(10) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ZONA VARCHAR(50) NOT NULL,
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    PRIMARY KEY (COD_ESPECTACULO, FECHA, HORA, COD_RECINTO, FILA, NUMERO, ZONA),
    FOREIGN KEY (COD_ESPECTACULO, FECHA, HORA) REFERENCES REPRESENTACIONES(COD_ESPECTACULO, FECHA, HORA),
    FOREIGN KEY (COD_RECINTO, ZONA, FILA, NUMERO) REFERENCES ASIENTOS(COD_RECINTO, ZONA, FILA, NUMERO),
    FOREIGN KEY (DNI_CLIENTE) REFERENCES ESPECTADORES(DNI_CLIENTE)
);

