CREATE TABLE PROVEEDORES(
  P VARCHAR(2),
  PNOMBRE VARCHAR(7),
  CATEGORIA INT,
  CIUDAD VARCHAR(10),
  PRIMARY KEY(P)
);

INSERT INTO PROVEEDORES (P, PNOMBRE, CATEGORIA, CIUDAD)
VALUES ('P1', 'CARLOS', 20, 'SEVILLA');
INSERT INTO PROVEEDORES (P, PNOMBRE, CATEGORIA, CIUDAD)
VALUES ('P2', 'JUAN', 10, 'MADRID');
INSERT INTO PROVEEDORES (P, PNOMBRE, CATEGORIA, CIUDAD)
VALUES ('P3', 'JOSE', 30, 'SEVILLA');
INSERT INTO PROVEEDORES (P, PNOMBRE, CATEGORIA, CIUDAD)
VALUES ('P4', 'INMA', 20, 'SEVILLA');
INSERT INTO PROVEEDORES (P, PNOMBRE, CATEGORIA, CIUDAD)
VALUES ('P5', 'EVA', 30, 'CACERES');
 
CREATE TABLE COMPONENTES (
  C VARCHAR(2),
  CNOMBRE VARCHAR(7),
  COLOR VARCHAR(5),
  PESO INT,
  CIUDAD VARCHAR(10),
  PRIMARY KEY(C)
);

INSERT INTO COMPONENTES (C, CNOMBRE, COLOR, PESO, CIUDAD)
VALUES ('C1', 'X3A', 'ROJO', 12, 'SEVILLA');
INSERT INTO COMPONENTES (C, CNOMBRE, COLOR, PESO, CIUDAD)
VALUES ('C2', 'B85', 'VERDE', 17, 'MADRID');
INSERT INTO COMPONENTES (C, CNOMBRE, COLOR, PESO, CIUDAD)
VALUES ('C3', 'C4B', 'AZUL', 17, 'MALAGA');
INSERT INTO COMPONENTES (C, CNOMBRE, COLOR, PESO, CIUDAD)
VALUES ('C4', 'C4B', 'ROJO', 14, 'SEVILLA');
INSERT INTO COMPONENTES (C, CNOMBRE, COLOR, PESO, CIUDAD)
VALUES ('C5', 'VT8', 'AZUL', 12, 'MADRID');
INSERT INTO COMPONENTES (C, CNOMBRE, COLOR, PESO, CIUDAD)
VALUES ('C6', 'C30', 'ROJO', 19, 'SEVILLA');
 
CREATE TABLE ARTICULOS (
  T VARCHAR(2),
  TNOMBRE VARCHAR(15),
  CIUDAD VARCHAR(10),
  PRIMARY KEY(T)
);

INSERT INTO ARTICULOS (T, TNOMBRE, CIUDAD)
VALUES ('T1', 'CLASIFICADORA', 'MADRID');
INSERT INTO ARTICULOS (T, TNOMBRE, CIUDAD)
VALUES ('T2', 'PERFORADORA', 'MALAGA');
INSERT INTO ARTICULOS (T, TNOMBRE, CIUDAD)
VALUES ('T3', 'LECTORA', 'CACERES');
INSERT INTO ARTICULOS (T, TNOMBRE, CIUDAD)
VALUES ('T4', 'CONSOLA', 'CACERES');
INSERT INTO ARTICULOS (T, TNOMBRE, CIUDAD)
VALUES ('T5', 'MEZCLADORA', 'SEVILLA');
INSERT INTO ARTICULOS (T, TNOMBRE, CIUDAD)
VALUES ('T6', 'TERMINAL', 'BARCELONA');
INSERT INTO ARTICULOS (T, TNOMBRE, CIUDAD)
VALUES ('T7', 'CINTA', 'SEVILLA');
 
CREATE TABLE ENVIOS (
  P VARCHAR(2) REFERENCES PROVEEDORES(P) ON DELETE SET NULL ON UPDATE CASCADE,
  C VARCHAR(2) REFERENCES COMPONENTES(C) ON DELETE SET NULL ON UPDATE CASCADE,
  T VARCHAR(2) REFERENCES ARTICULOS(T) ON DELETE SET NULL ON UPDATE CASCADE,
  CANTIDAD INT,
  PRIMARY KEY(P, C, T)
);
 
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P1', 'C1', 'T1', 200);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P1', 'C1', 'T4', 700);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P2', 'C3', 'T1', 400);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P2', 'C3', 'T2', 200);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P2', 'C3', 'T3', 200);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P2', 'C3', 'T4', 500);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P2', 'C3', 'T5', 600);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P2', 'C3', 'T6', 400);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P2', 'C3', 'T7', 800);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P2', 'C5', 'T2', 100);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P3', 'C3', 'T1', 200);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P3', 'C4', 'T2', 500);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P4', 'C6', 'T3', 300);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P4', 'C6', 'T7', 300);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C2', 'T2', 200);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C2', 'T4', 100);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C5', 'T4', 500);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C5', 'T7', 100);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C6', 'T2', 200);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C1', 'T4', 100);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C3', 'T4', 200);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C4', 'T4', 800);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C5', 'T5', 400);
INSERT INTO ENVIOS(P, C, T, CANTIDAD)
VALUES ('P5', 'C6', 'T4', 500);

/* Ejercicios 
1 - Obtener todos los detalles de todos los artículos de CACERES
SELECT * FROM `ARTICULOS` WHERE CIUDAD = 'CACERES';

2- Obtener todos los valores de P# para los proveedores que abastecen el artículo T1. 
SELECT P FROM ENVIOS WHERE T = 'T1';  

3- Obtener  la  lista  de  pares  de  atributos  (COLOR,  CIUDAD)  de  la  tabla  componentes  eliminando los pares duplicados
SELECT DISTINCT COLOR, CIUDAD FROM `COMPONENTES`;

4- Obtener  de  la  tabla  de  artículos  los  valores  de  T#  y  CIUDAD  donde  el  nombre  de  la  ciudad acaba en D o contiene al menos una E. 
SELECT T, CIUDAD FROM `ARTICULOS` WHERE CIUDAD LIKE '%D%' OR CIUDAD LIKE '%E%';
Obtener  los  valores  de  P#  para  los  proveedores  que  suministran  para  el  artículo  T1  el  componente C1. 
SELECT P FROM ENVIOS WHERE T = 'T1' AND C = 'C1';

6.Obtener los valores de TNOMBRE en orden alfabético para los artículos abastecidos por el proveedor P1. 
SELECT TNOMBRE FROM `ARTICULOS` WHERE CIUDAD = 'MADRID';

7.Obtener los valores de C# para los componentes suministrados para cualquier artículo de MADRID. 
SELECT C FROM ENVIOS WHERE T IN (SELECT T FROM ARTICULOS WHERE CIUDAD = 'MADRID');

8.Obtener  todos  los  valores  de  C#  de  los  componentes  tales  que  ningún  otro  componente    tenga un valor de peso inferior. 
SELECT C FROM COMPONENTES WHERE PESO = (SELECT MAX(PESO) FROM COMPONENTES);

9.Obtener los valores de P# para los proveedores que suministren los artículos T1 Y T2 ambos proveedores deben de suministrar los dos artículos
hazlo con una subconsulta que primero consulte t1 y luego t2 y luego los proveedores que suministran los dos artículos
como seria asi 
SELECT P FROM ENVIOS WHERE T = 'T1' AND P IN (SELECT P FROM ENVIOS WHERE T = 'T2');






*/

